@startuml
entity "Sala" {
  + id [PK]
  --
  + name
  + capacity
}

entity "People" {
  + id [PK]
  --
  + name
  + surname
  + email
  + password
  + role
}

entity "Reservation" {
  + id [PK]
  --
  + date
  + time
  + people
  + sala_id [FK]
  + people_id [FK]
}
@enduml
